### ISSUE TITLE
Incorrect implementation of AutofacMvxIocProvider.IoCConstruct(Type type)

### ISSUE THREAD

**Issue by lauxjpn** [autofac/Autofac.Extras.MvvmCross#5]
The implementation of `public virtual object IoCConstruct(Type type)` in "AutofacMvxIocProvider.cs" seems to be not in accordance with the intended behavior of MvvmCross.

The current implementation in the `AutofacMvxIocProvider` class just delegates the method call to the `Resolve` method, making it the same as calling the `Resolve` method in the first place.

If you take a look at the implementation of the `IoCConstruct` method in the `MvxSimpleIoCContainer` class, you can see that it is intended and implemented as a generalized mechanism to directly create a class instance of any class (without looking up any registration first), but then resolving any constructor parameters and properties in a usual IOC manner.

A side effect of the current implementation is that any view model cannot just be created automatically by MvvmCross but has to be explicitly registered with Autofac first before usage.

**Comment by tillig** [comment]
Unfortunately, the Autofac maintainers (myself included) aren't really MvvmCross users - this integration was somewhat of a "drive-by contribution" that the community has maintained for the most part. The current implementation is based on various pull requests we've received and integrated..

[It does appear we have a unit test](https://github.com/autofac/Autofac.Extras.MvvmCross/blob/develop/test/Autofac.Extras.MvvmCross.Test/AutofacMvxIocProviderFixture.cs#L248) that indicates the `IoCConstruct` method _should throw_ if the view model isn't registered. At least, that was the intention when the implementation was written.

Something to consider: Autofac requires _everything be registered_ that you want in the IoC system. This is slightly different than how some IoC containers work. For example, simple IoC containers like those that come with ASP.NET MVC have a sort of "fallback" where it will call `Activator.CreateInstance` on types that aren't registered. That's an intentional design difference in Autofac - everything has to be registered and there is no fallback.

That could be why the current implementation just calls `Resolve`: It intentionally is using Autofac in the way Autofac is naturally used. Whether this is at odds with what MvvmCross expects or what you, personally, expect isn't something I can speak to.

However, we are happy to take pull requests with accompanying tests. If you believe the code is incorrect, you are welcome to submit an appropriate fix.

**Comment by alexmg** [comment]
You may also be able to use the `AnyConcreteTypeNotAlreadyRegisteredSource` to achieve the desired behaviour.

http://autofac.readthedocs.io/en/latest/advanced/registration-sources.html#any-concrete-type-not-already-registered-source

**Comment by tillig** [comment]
I filed #8 indicating that there are lots of uses of `ContainerBuilder.Update` in `AutofacMvxIocProvider` and we're trying to deprecate `Update`. If we went with ACTNARS as the solution here that might kill two birds with one stone.

**Comment by tillig** [comment]
Version 5.0.0 has been released with some changes to accommodate support for MvvmCross 6.2.0. I'm not sure if this issue is still a problem or if ACTNARS can resolve it, but since there were some pretty big changes I'm going to close it. If it turns out this is still a problem for folks, we can re-open... but really will need a PR to fix it with some concrete suggestion about how this needs to be solved.
